#ifndef _CTIOT_DEVICE_INFO_H
#define _CTIOT_DEVICE_INFO_H

#define DEVICE_NO "001"
#define DEVICE_ID "10029135001"
#define DEVICE_PROTOCOL "MQTT"
#define DEVICE_AUTHORIZATION "token"
#define DEVICE_TOKEN "0HMySQVFMsXe3hiNH-O2-v87t7NUaQDXRdL7OJHA3yE"
#define DEVICE_TRANSPARENT 0
#define DEVICE_TCPADDRESS "mqtt.ctwing.cn"
#define DEVICE_TCPPORT "1883"
#define DEVICE_TLSADDRESS "mqtt.ctwing.cn"
#define DEVICE_TLSPORT "8883"

#endif //_CTIOT_DEVICE_INFO_H

